######################################################################
#
# File name : lpdc_test_TB_simulate.do
# Created on: Mon Nov 13 16:01:18 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L fifo_generator_v13_2_1 -L blk_mem_gen_v8_4_1 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.lpdc_test_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {lpdc_test_TB_wave.do}

view wave
view structure
view signals

do {lpdc_test_TB.udo}

run 1000ns
