######################################################################
#
# File name : lpdc_test_TB_compile.do
# Created on: Mon Nov 13 16:01:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim\\win64\\vlib modelsim_lib/work
D:\\modelsim\\win64\\vlib modelsim_lib/msim

D:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib
D:\\modelsim\\win64\\vlib modelsim_lib/msim/fifo_generator_v13_2_1
D:\\modelsim\\win64\\vlib modelsim_lib/msim/blk_mem_gen_v8_4_1

D:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
D:\\modelsim\\win64\\vmap fifo_generator_v13_2_1 modelsim_lib/msim/fifo_generator_v13_2_1
D:\\modelsim\\win64\\vmap blk_mem_gen_v8_4_1 modelsim_lib/msim/blk_mem_gen_v8_4_1

D:\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0" \
"../../../../lpdc_test_ex.ip_user_files/ip/ila_0/sim/ila_0.v" \

D:\\modelsim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_1  "+incdir+../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0" \
"../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/fifo_generator_0/simulation/fifo_generator_vlog_beh.v" \

D:\\modelsim\\win64\\vcom -64 -93 -work fifo_generator_v13_2_1  \
"../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.vhd" \

D:\\modelsim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_1  "+incdir+../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0" \
"../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.v" \

D:\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \

D:\\modelsim\\win64\\vlog -64 -incr -work blk_mem_gen_v8_4_1  "+incdir+../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0" \
"../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/H1/simulation/blk_mem_gen_v8_4.v" \

D:\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/clk_wiz_0" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/H1/sim/H1.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/H2/sim/H2.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/h3/sim/h3.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/H4/sim/H4.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/ila_0/sim/ila_0.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ipshared/3f9f/ldpc_fifo/ldpc_fifo.srcs/sources_1/imports/Desktop/encode.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ipshared/3f9f/ldpc_fifo/ldpc_fifo.srcs/sources_1/imports/new/fifo_control.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ipshared/3f9f/ldpc_fifo/ldpc_fifo.srcs/sources_1/imports/code/ldpc.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ipshared/3f9f/ldpc_fifo/ldpc_fifo.srcs/sources_1/new/top_test.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/ip/ldpc_ldpc_1_0_0/sim/ldpc_ldpc_1_0_0.v" \
"../../../../lpdc_test_ex.ip_user_files/bd/ldpc/sim/ldpc.v" \
"../../../../lpdc_test_ex.srcs/sources_1/ip/lpdc_test/lpdc_test_sim_netlist.v" \
"../../../../lpdc_test_ex.srcs/sources_1/bd/ldpc/hdl/ldpc_wrapper.v" \
"../../../../lpdc_test_ex.srcs/sources_1/imports/example_design/support/lpdc_test_common.v" \
"../../../../lpdc_test_ex.srcs/sources_1/imports/example_design/support/lpdc_test_common_reset.v" \
"../../../../lpdc_test_ex.srcs/sources_1/imports/example_design/lpdc_test_exdes.v" \
"../../../../lpdc_test_ex.srcs/sources_1/imports/example_design/lpdc_test_gt_frame_gen.v" \
"../../../../lpdc_test_ex.srcs/sources_1/imports/example_design/support/lpdc_test_gt_usrclk_source.v" \
"../../../../lpdc_test_ex.srcs/sources_1/imports/example_design/support/lpdc_test_support.v" \
"../../../../lpdc_test_ex.srcs/sim_1/imports/simulation/lpdc_test_tb.v" \

# compile glbl module
D:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

