######################################################################
#
# File name : lpdc_test_TB_wave.do
# Created on: Mon Nov 13 15:50:02 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
