# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/doinc/Desktop/decode_final_test/test_ldpc_5tongdao/test_ldpc.srcs/sources_1/ip/H3_4/H3_4.xci
# IP: The module: 'H3_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/decode_final_test/test_ldpc_5tongdao/test_ldpc.srcs/sources_1/ip/H3_4/H3_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H3_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/doinc/Desktop/decode_final_test/test_ldpc_5tongdao/test_ldpc.srcs/sources_1/ip/H3_4/H3_4.xci
# IP: The module: 'H3_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/decode_final_test/test_ldpc_5tongdao/test_ldpc.srcs/sources_1/ip/H3_4/H3_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'H3_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
