# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/doinc/Desktop/test_ldpc_2gai/test_ldpc.srcs/sources_1/ip/decode/decode.xci
# IP: The module: 'decode' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/test_ldpc_2gai/test_ldpc.srcs/sources_1/ip/decode/decode.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/test_ldpc_2gai/test_ldpc.srcs/sources_1/ip/decode/decode_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/doinc/Desktop/test_ldpc_2gai/test_ldpc.srcs/sources_1/ip/decode/decode.xci
# IP: The module: 'decode' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/test_ldpc_2gai/test_ldpc.srcs/sources_1/ip/decode/decode.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/doinc/Desktop/test_ldpc_2gai/test_ldpc.srcs/sources_1/ip/decode/decode_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'decode'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
