# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/decode_exds.xdc

# IP: ip/ila_1/ila_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_1 || ORIG_REF_NAME==ila_1} -quiet] -quiet

# IP: ip/ten_bit/ten_bit.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ten_bit || ORIG_REF_NAME==ten_bit} -quiet] -quiet
