# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/doinc/Desktop/my_ldpc/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/h3/h3.xci
# IP: The module: 'h3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/my_ldpc/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/h3/h3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'h3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/doinc/Desktop/my_ldpc/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/h3/h3.xci
# IP: The module: 'h3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doinc/Desktop/my_ldpc/ldpc_fifo/ldpc_fifo.srcs/sources_1/ip/h3/h3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'h3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
