# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in.xci
# IP: The module: 'fifo_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_in'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in.xci
# IP: The module: 'fifo_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Administrator/Desktop/decode/test_ldpc/test_ldpc.srcs/sources_1/ip/fifo_in/fifo_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
